                               #######             
                              #                    
        ############ -#####+.##     ######         |	DataDrivenConstruction.io
        ##+########## .-##+ #-   .+########        |	
        ####     ####.     ..    #      ###        |	Dive into the future of flexibility in processing data 
        ####     .#+#.     #    .# .               |	without using BIM tools!
        ####     -#+#.    #.     .#.               |	
        ####      #+#.   ##-                       |	
        ####     ####        #.  #     -####       |	
        ############  .###+ #. ############        |
        #########.   +#### #+.   ########          |	If you have any questions, concerns or special requests,
                           #+                      |	please contact us at info@datadrivenconstruction.io	
                          #                        
                         #  

In [ ]:
############################ WARNING ############################
#
# pythonOCC and py-qt5 (or pyside2) libraries are needed to run the Script
#
# Links:
# pythonOCC - https://github.com/tpaviot/pythonocc-core
#
# Instruction:
# First Method (Anaconda)
# 1. Create an environment
#
#    conda create --name=pyoccenv python=3.9
#    source activate pyoccenv
#
# 2. Install library
#
#    conda install -c conda-forge pythonocc-core=7.7.0
#
# 3. Install pyqt5 (or pyside2)
#
#   pip install pyqt5
#
# Second Method (Manual)
#
# 1. Download the archive from the link
#    https://drive.google.com/file/d/1qJJPlHopBoKhgroo0VWtFGOLUI32V2bN/view
# 2. Move the contents of the archive to the Python directory
#
#    Default Python directory
#    C:\Python39; C:\Users\YourUser\AppData\Local\Programs\Python\Python39
#
#    For example, folder "libs" in the archive should merge with the folder "libs" in the Python directory
#    Files in the root of the archive should be in the root of the Python directory
#
# 3. Install pyqt5 (or pyside2)
#
#    pip install pyqt5
#
#  End Instruction
#
# To check the correct installation, run below code
# from OCC.Display.SimpleGui import init_display
# from OCC.Core.BRepPrimAPI import BRepPrimAPI_MakeBox
# display, start_display, _, _ = init_display()
# my_box = BRepPrimAPI_MakeBox(10.0, 20.0, 30.0).Shape()
# display.DisplayShape(my_box, update=True)
# start_display()
#
############################ END WARNING ############################

In [6]:
import trimesh
file_name = r'C:\DataDrivenConstruction\DATA\Sample\Data\Revit\rst_advanced_sample_project.dae'
mesh = trimesh.load(file_name)

scene_with_mesh = load(file_name, force='scene')
viewer.notebook.scene_to_notebook(scene_with_mesh)

In [10]:
mesh.export(r'C:\DataDrivenConstruction\rst_advanced_sample_project.gltf')
mesh.export(r'C:\DataDrivenConstruction\rst_advanced_sample_project.obj')

'# https://github.com/mikedh/trimesh\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.mtl\nmtllib material_0.m

In [1]:
# Example of displaying geometry in Jupyter Notebook
from trimesh import load, viewer
path = r"C:\DataDrivenConstruction\Reports\walls.dae"
scene_with_mesh = load(path, force='scene')
viewer.notebook.scene_to_notebook(scene_with_mesh)

C:\Users\Artem\anaconda5\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [11]:
C:\DataDrivenConstruction\
mesh.save_image()

C:\Users\Artem\anaconda5\lib\site-packages\pyglet\image\codecs\wic.py:406: UserWarning: [WinError -2147417850] Cannot change thread mode after it is set
  warnings.warn(str(err))


b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x07\x08\x00\x00\x05F\x08\x06\x00\x00\x00\x8a^\xef\xb3\x00\x00\x00\x01sRGB\x00\xae\xce\x1c\xe9\x00\x00\x00\x04gAMA\x00\x00\xb1\x8f\x0b\xfca\x05\x00\x00\x80\xf2IDATx^\xec\xdd\xfb\x92\x1c\xd5a\xc0\xe1\xde\xab\xa4Ew@\x0eX\xceJ+\xb0\xb9\xc9@p\x086\xe0G\xd0\xbfT\x81\xf3\x1az\x83\xfc\xa3\xe7\x88\x9f !\x0f`;q*\xc4\xae\x88*\xbb\xc0h\x05\x0bR\xb8I\xab\x9b\x03\x92\xf6\x16No\x9f\xa5wvvvfv.\xdd}\xbe\xaf\xea\xd4\x9c\x9d\xd9YHm\x87\x93\x9c\xdf\x9e\x9e\x89\x8d\xefd0\x00\xbf\xfa\xd5\xaf2\x97\x13\x00U611a\xad\xa2\x12~\xfd\xeb_\x173\x00\x00\x00\x80\xd1\x13\x08\x19\x98\x10\x08\x03\x97\x14\x00U\x15\x02ad\xbd\x02\x80\xf1\xf3\x07\x13\x00\x000\x1e\x02!\x03\x13\x03a\xe4\xd2\x02\xa0j\xca\x810\xb2^\x01@}\t\x8c\x00\x00\xd0\x9f\xc9\xe2\x11\x06\xae\xdd&,\x00T\x8d\xf5\n\x00\x00\x00\x80\xd4\x08\x84\x0c\x95MW\x00\xea \xacW\xd6,\x00\x00\x00\x00R!\x102t6]\x01\xa8\x0bk\x16\x00\x00\x00\x00)\x10\x08\x19\x19\x1b\xae\x00\xd4\x85P\x08\x00\x00\x00@\x93\t\x84\x8c\x94\rW\x00\xea\xc4\

In [9]:
#BoundaryBox
mesh.bounds_corners

array([[ 66.86184692, -18.91540909, 124.01570129],
       [ 76.00534821, -18.91540909, 124.01570129],
       [ 76.00534821,  -2.35483289, 124.01570129],
       ...,
       [ 42.68423843, -40.87900925, 146.65350342],
       [ 42.68423843, -40.30805969, 146.65350342],
       [ 42.28149033, -40.30805969, 146.65350342]])

In [10]:
mesh.centroid

array([ 53.35461998, -20.74270916, 135.49549866])

In [12]:
mesh.bounds

array([[ 23.70882034, -67.45555878, 119.9803009 ],
       [ 83.00041962,  25.97014046, 151.01069641]])

In [11]:
mesh.bounding_primitive

<trimesh.primitives.Box>

In [2]:
from trimesh import load, viewer
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from datetime import datetime


#Path to project files
pathf = r'C:\\Users\\Downloads\check\\'
v1name = 'Projekt Version1_25052022'
v2name = 'Projekt_Version2_17052022'
project_v1 = pd.read_csv(pathf+v1name+'.csv', low_memory=False, index_col = 0)
project_v2 = pd.read_csv(pathf+v2name+'.csv', low_memory=False, index_col = 0)


df1 = project_v1.compare(project_v2, align_axis=1).rename(columns={'self': 'Version1', 'other': 'Version2'}, level=-1)
df1['Volume'] = df1['Volume'].replace('m³', '', regex=True)
df1['Area'] = df1['Area'].replace('m²', '', regex=True)

df1[('Volume','Version1')] = pd.to_numeric(df1[('Volume','Version1')])
df1[('Volume','Version2')] = pd.to_numeric(df1[('Volume','Version2')])
df1[('Area','Version1')] = pd.to_numeric(df1[('Area','Version1')])
df1[('Area','Version2')] = pd.to_numeric(df1[('Area','Version2')])

df2 = pd.DataFrame(df1, columns=[('Volume','Version1'), ('Volume','Version2')])


# Form geometries for individual groups - in this case, groups of modified elements

group_ids = df2.index
#print(group_ids)

group_ids_str = []
for el in group_ids:
    group_ids_str.append(str(el))
#group_ids_str

import os
import xml.etree.ElementTree as ET
import copy

path = r'C:\\Users\\Downloads\check\\'
file = 'Projekt Version1_25052022.dae'
fileObject = open(path+'/'+file, "r")
print(fileObject)

transparency_ratio = '0.1'
color_for_differences =  '0.8 0.3 0.1 1'


ET.register_namespace("", "http://www.collada.org/2005/11/COLLADASchema")

tree = ET.parse(fileObject)
root = tree.getroot()
#removeList = [instance_geometry]
geom_list = []




#material_list
material_list = []
effect_list = []
for node in root.findall('.//{http://www.collada.org/2005/11/COLLADASchema}node'):
    #print(a.attrib)
    
    if node.attrib['id'] in group_ids_str:
        url = list(node)[0].get('url')
        geom_list.append(url[1:])

        #add material id to material list
        target = list(node)[0][0][0][0].attrib['target']
        list(node)[0][0][0][0].attrib['target'] = target.replace('#ID', '#GREEN')
  
        if not target[1:] in material_list:
        	material_list.append(target[1:])
        	effect_list.append(target[1:].replace('material', 'effect'))
        

library_materials = root.find(".//{http://www.collada.org/2005/11/COLLADASchema}library_materials")

for material in material_list:

	el = ET.Element('material')
	value = material.replace('ID', 'GREEN')
	el.set('id', value)
	el.set('name', value)
	s_el = ET.SubElement(el, 'instance_effect')
	s_el.set('url', '#' + value.replace('material', 'effect'))
	library_materials.insert(0, el)


library_effects = root.find(".//{http://www.collada.org/2005/11/COLLADASchema}library_effects")	
for effect in root.findall(".//{http://www.collada.org/2005/11/COLLADASchema}effect"):

	id_ = effect.attrib['id']
	if id_ in effect_list:

		green_effect = copy.deepcopy(effect)
		green_effect.attrib['id'] = id_.replace('ID', 'GREEN')

		ambient_color = green_effect.find('.//{http://www.collada.org/2005/11/COLLADASchema}ambient/{http://www.collada.org/2005/11/COLLADASchema}color')
		ambient_color.text = color_for_differences

		diffuse_color = green_effect.find('.//{http://www.collada.org/2005/11/COLLADASchema}diffuse/{http://www.collada.org/2005/11/COLLADASchema}color')
		diffuse_color.text = color_for_differences

		library_effects.insert(0, green_effect)

	transparency = ET.Element('transparency')
	float_ = ET.SubElement(transparency, 'float')
	float_.text = transparency_ratio
	effect[0][0][0].insert(0, transparency)

file_name = 'C:\\Users\\Artem\\Downloads\\check\\Checking_Changes_Version2.dae'
tree.write(file_name)
#path = r"C:\BIMJSON\Red Sea\Reports\walls.dae"
scene_with_mesh = load(file_name, force='scene')
viewer.notebook.scene_to_notebook(scene_with_mesh, height=800)

<_io.TextIOWrapper name='C:\\\\Users\\\\Artem\\\\Downloads\\check\\\\/Projekt Version1_25052022.dae' mode='r' encoding='cp1252'>


In [6]:
mesh.geometry_identifiers

<trimesh.primitives.Box>

In [13]:
mesh.duplicate_nodes

[['shape773-lib.0'],
 ['shape774-lib.0'],
 ['shape775-lib.0'],
 ['shape776-lib.0'],
 ['shape777-lib.0'],
 ['shape778-lib.0'],
 ['shape779-lib.0'],
 ['shape780-lib.0'],
 ['shape781-lib.0'],
 ['shape782-lib.0'],
 ['shape783-lib.0'],
 ['shape784-lib.0'],
 ['shape785-lib.0'],
 ['shape786-lib.0'],
 ['shape787-lib.0'],
 ['shape788-lib.0'],
 ['shape789-lib.0'],
 ['shape790-lib.0'],
 ['shape791-lib.0'],
 ['shape792-lib.0'],
 ['shape793-lib.0'],
 ['shape794-lib.0'],
 ['shape795-lib.0'],
 ['shape796-lib.0'],
 ['shape797-lib.0'],
 ['shape798-lib.0', 'shape799-lib.0'],
 ['shape800-lib.0'],
 ['shape801-lib.0'],
 ['shape802-lib.0'],
 ['shape803-lib.0', 'shape807-lib.0'],
 ['shape804-lib.0'],
 ['shape805-lib.0'],
 ['shape806-lib.0', 'shape810-lib.0'],
 ['shape808-lib.0'],
 ['shape809-lib.0'],
 ['shape811-lib.0'],
 ['shape812-lib.0'],
 ['shape813-lib.0'],
 ['shape814-lib.0'],
 ['shape815-lib.0'],
 ['shape816-lib.0'],
 ['shape817-lib.0'],
 ['shape818-lib.0'],
 ['shape819-lib.0'],
 ['shape820-lib.0', 's

In [15]:
mesh.area

40439.97648220195

In [7]:
help(mesh)

Help on Scene in module trimesh.scene.scene object:

class Scene(trimesh.parent.Geometry3D)
 |  Scene(geometry=None, base_frame='world', metadata={}, graph=None, camera=None, lights=None, camera_transform=None)
 |  
 |  A simple scene graph which can be rendered directly via
 |  pyglet/openGL or through other endpoints such as a
 |  raytracer. Meshes are added by name, which can then be
 |  moved by updating transform in the transform tree.
 |  
 |  Method resolution order:
 |      Scene
 |      trimesh.parent.Geometry3D
 |      trimesh.parent.Geometry
 |      abc.ABC
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __add__(self, other)
 |      Concatenate the current scene with another scene or mesh.
 |      
 |      Parameters
 |      ------------
 |      other : trimesh.Scene, trimesh.Trimesh, trimesh.Path
 |         Other object to append into the result scene
 |      
 |      Returns
 |      ------------
 |      appended : trimesh.Scene
 |         Scene with geometr